version: '3.7'
name: 'cinema'

services:
  backend:
    build: ./backend
    container_name: backend
    restart: always
    volumes:
      - static:/opt/app/static
      - media:/opt/app/media
    networks:
      - cinema-network
    depends_on:
      - db
    environment:
      - DJANGO_SECRET_KEY
      - DEBUG
      - ALLOWED_HOSTS
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_SEARCH_PATHS

  etl:
    build: ./etl
    container_name: etl
    restart: always
    networks:
      - cinema-network
    depends_on:
      - db
      - elastic-search
      - redis
      - backend  # because of migrations
    environment:
      - DEBUG
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST
      - POSTGRES_PORT
      - ELASTIC_SEARCH_PORT
      - ELASTIC_SEARCH_HOST
      - ELASTIC_SEARCH_MOVIES_INDEX
      - ELASTIC_SEARCH_MOVIES_INDEX_PATH
      - REDIS_HOST
      - REDIS_PORT
      - REDIS_DB

  db:
    image: postgres:${POSTGRES_TAG}
    container_name: db
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data/
    ports:
      - '5432:5432'
    networks:
      - cinema-network
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST
      - POSTGRES_PORT

  redis:
    image: redis:${REDIS_TAG}
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    networks:
      - cinema-network

  elastic-search:
    image: elasticsearch:${ELASTIC_SEARCH_TAG}
    container_name: elastic
    restart: always
    networks:
      - cinema-network
    ports:
      - '9200:9200'
    environment:
      - discovery.type=${ELASTIC_SEARCH_DISCOVERY_TYPE}
      - xpack.security.enabled=${ELASTIC_SEARCH_XPACK_SECURITY_ENABLED}

  nginx:
    image: nginx:${NGINX_TAG}
    container_name: nginx
    restart: always
    volumes:
      - media:/var/html/media
      - static:/var/html/static
      - ./configs/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs/nginx.default.conf.template:/etc/nginx/templates/default.conf.template:ro
    depends_on:
      - backend
    ports:
      - '80:80'
    networks:
      - cinema-network
    environment:
      - NGINX_HOST

networks:
  cinema-network:
    driver: bridge

volumes:
  media:
  static:
  db-data:
