version: '3.7'
name: 'movies-project'

services:
  backend:
    build: ./backend
    container_name: backend
    restart: always
    volumes:
      - static:/opt/app/static
      - media:/opt/app/media
    networks:
      - movies-network
    depends_on:
      - db
    environment:
      - DJANGO_SECRET_KEY
      - DEBUG
      - ALLOWED_HOSTS
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_SEARCH_PATHS

  db:
    image: postgres:${POSTGRES_TAG}
    container_name: db
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data/
    networks:
      - movies-network
    # TODO: close all ports after development
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST
      - POSTGRES_PORT

  nginx:
    image: nginx:${NGINX_TAG}
    container_name: nginx
    volumes:
      - media:/var/html/media
      - static:/var/html/static
      - ./configs/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs/nginx.default.conf.template:/etc/nginx/templates/default.conf.template:ro
    depends_on:
      - backend
    ports:
      - '80:80'
    networks:
      - movies-network
    environment:
      - NGINX_HOST

networks:
  movies-network:
    driver: bridge

volumes:
  media:
  static:
  db-data:
