version: '3.7'
name: 'movies-project'

services:
  backend:
    build: ./app
    container_name: backend
    restart: always
    volumes:
      - static:/app/media
      - media:/app/static
    networks:
      - movies-network
    env_file:
      - ./configs/.env
    depends_on:
      - db

  db:
    image: postgres:${POSTGRES_TAG}
    container_name: db
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data/
    networks:
      - movies-network
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST
      - POSTGRES_PORT

  nginx:
    image: nginx:${NGINX_TAG}
    container_name: nginx
    volumes:
      - media:/var/html/media
      - static:/var/html/static
      - ./configs/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs/nginx.default.conf.template:/etc/nginx/templates/default.conf.template:ro
    depends_on:
      - backend
    ports:
      - '80:80'
    networks:
      - movies-network
    environment:
      - NGINX_HOST

networks:
  movies-network:
    driver: bridge

volumes:
  media:
    driver: local
  static:
    driver: local
  db-data:
    driver: local
